#!/bin/bash

set -e

# Check if $PKG_CMD has been provided
if [[ -z $PKG_CMD ]]; then
    echo 'Error: "$PKG_CMD" is not defined, please set this to your package manager install command'
    echo 'e.g.:'
    echo '    ubuntu: "apt install"'
    echo '    fedora: "dnf install"'
    echo '    arch:   "pacman -S"'
    exit 1
fi

# In case zsh is missing, install it and oh-my-zsh
if ! which zsh &>/dev/null; then
    # For how the script works do this separately
    # Install oh-my-zsh in the most unsafe way
    echo "zsh is not installed"
    echo "Installing zsh and oh-my-zsh"
    sudo $PKG_CMD zsh
    chsh -s $(which zsh)
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    echo "Please run '.condfig/base_setup' again"
fi

# Installing chezmoi to push local changes
echo Installing chezmoi
sh -c "$(curl -fsLS get.chezmoi.io)"
    
# Make executables executable
# for file in ~/.local/bin*; do chmod 755 "$file"; done
# (Handled by chezmoi)

# Add entry to .zshrc to load config
echo '' >> ~/.zshrc
echo '# Include zsh configuration' >> ~/.zshrc
echo 'for file in ~/.config/zsh/*; do source "$file"; done' >> ~/.zshrc

# install needed packages
sudo $PKG_CMD \
	sway \
	foot \
	kitty \
	neovim \
	mpv \
	bemenu \
	swaylock \
	swayidle \
	waybar \
	swaybg \
	grim \
	wl-clipboard \
	brightnessctl \
	zsh-autosuggestions \
	zsh-syntax-highlighting \
	syncthing \
	emacs \
	slurp \
	wireguard

# Find another way to install fonts
# ttf-nerd-fonts-symbols
