#!/bin/bash

sudo pacman -S\
	sway\
	foot\
	kitty\
	neovim\
	mpv\
	bemenu\
	swaylock\
	swayidle\
	waybar\
	swaybg\
	grim\
	wl-clipboard\
	brightnessctl\
	ttf-nerd-fonts-symbols\
	zsh-autosuggestions\
	zsh-syntax-highlighting\
	zsh\
	syncthing\
	emacs\
	slurp
