#!/bin/zsh

# Define any custom variable

# Funny path used by chezmoi
export PATH="$HOME/bin:$PATH"

# Add local bins to PATh
export PATH="$HOME/.local/bin:$PATH"

# Add doomemacs to PATH
export PATH="$HOME/.config/emacs/bin:$PATH"

# Add gem executables to path
export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"

# Some variables to make sure applications works under wayland
export XDG_CONFIG_HOME="$HOME/.config"

# resolve bundle permissions
export BUNDLE_PATH=$HOME/.bundle/

# default editor and pager
export PAGER=less
# EDITOR: depending on user choice, can be:
# - nvim
# - emacs
# - emacsclient -a 'emacs'
export EDITOR="nvim"
