#!/bin/zsh

export RUSTC_WRAPPER="/opt/homebrew/bin/sccache"

# Define any custom variable
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# Funny path used by chezmoi
export PATH="$HOME/bin:$PATH"

# Add local bins to PATh
export PATH="$HOME/.local/bin:$PATH"

# Some variables to make sure applications works under wayland
export XDG_CONFIG_HOME="$HOME/.config"

# default editor and pager
export PAGER=less
export EDITOR=nvim
