#!/bin/zsh

# Aliases for zsh
# listing aliases
alias ls='ls --color=auto'
alias ll='ls -al'

# save my ass
alias rm='echo "use \"trash\" or \"/usr/bin/rm\""'

# I will never type nvim
alias vim='nvim'

# Python's brainfart
alias python="python3"
