#!/bin/zsh
if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then

    DATE=$(date +"%Y-%m-%d_%H-%M-%S")
    echo "==$DATE" > "/tmp/sway.log"
    echo "==$DATE" > "/tmp/sway.err"

    source $HOME/.config/sway/startup_var
    exec sway --unsupported-gpu\
        >> "/tmp/sway.log" \
        2>> "/tmp/sway.err"
fi
