#!/bin/zsh

# Aliases for zsh

alias ls='ls --color=auto'
alias rm='rm -i'
alias ll='ls -al'
alias v='nvim'
alias vi='v'
alias vim='v'
alias e="emacsclient -c -a 'emacs'"
alias em="e"
alias emacs="e"
