#!/bin/zsh

# Aliases for zsh

alias ls='ls --color=auto'
alias rm='rm -i'
alias ll='ls -al'
alias vim='nvim'
alias vi='nvim'
alias v='nvim'
alias emacs="emacsclient -c -a 'emacs'"
alias em="emacsclient -c -a 'emacs'"
alias e="emacsclient -c -a 'emacs'"
