#!/bin/zsh

# initial setup, be sure to source this into your .zshrc

source $HOME/.config/zsh/sh_variables
source $HOME/.config/zsh/sh_aliases
source $HOME/.config/zsh/sh_bindings

if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    source $HOME/.config/sway/startup_var
    exec sway
fi
