#!/bin/zsh

# Define any custom variable

# Add doomemacs to PATH
export PATH="$HOME/.config/emacs/bin:$PATH"

# Some variables to make sure applications works under wayland
export XDG_CONFIG_HOME="$HOME/.config"
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt5ct
export GTK_BACKEND=wayland

# default editor and pager
export EDITOR="emacslient -c -a 'emacs'"
export PAGER=less
