# For config refer to official docs to
# https://greshake.github.io/i3status-rust/i3status_rs/blocks/index.html

icons_format = "{icon}"

[theme]
theme = "palette.toml"

[icons]
icons = "icons.toml"

[[block]]
block = "net"
format = " $icon {$ssid ($signal_strength)} "

[[block]]
block = "sound"
format = "$icon $output_name{ $volume|}"
[block.mappings]
"bluez_output.00_1B_66_0F_26_BD.1"  = "HD 450SE"
"audio_effect.j313-convolver"       = "Speakers"
"alsa_output.platform-sound.HiFi__hw_AppleJ313_0__sink" = "Jack audio"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = "$icon $mem_total_used_percents.eng(w:2)"
format_alt = "$icon_swap $swap_used_percents.eng(w:2)"

[[block]]
block = "backlight"

[[block]]
block = "battery"
format = "$icon $percentage"

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "🌐 $layout"
[block.mappings]
"English (Colemak-DH ISO)" = "Col-DH_ISO"
"English (US)" = "qwerty_US"

[[block]]
block = "time"
interval = 5
format = "$icon $timestamp.datetime(f:'%R | %d/%m')"

[[block]]
block = "pomodoro"
notify_cmd = "swaynag -m '{msg}'"
blocking_cmd = true
