#!/bin/sh

set -e

# Check if $PKG_CMD has been provided
if [[ ( -z $PKG ) || ( -z $INSTALL_CMD ) ]]; then
    echo 'Error: "$PKG" or "$INSTALL_CMD" are not defined, please set this to your package manager install command'
    echo 'e.g.:'
    echo '    ubuntu: "apt" and "install"'
    echo '    fedora: "dnf" "install"'
    echo '    arch:   "pacman" and "-S"'
    exit 1
fi


if ! which git &>/dev/null; then
    echo "git not installed"
    echo "installing git"
    sudo $PKG $INSTALL_CMD git
fi

# In case zsh is missing, install it and oh-my-zsh
if ! which zsh &>/dev/null; then
    # For how the script works do this separately
    # Install oh-my-zsh in the most unsafe way
    echo "zsh is not installed"
    echo "installing zsh"
    sudo $PKG $INSTALL_CMD zsh
    chsh -s $(which zsh)
    echo "Please run '.condfig/base_setup/stage0' again"
    exit 1
fi

echo "Installing oh-my-zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

zsh ~/.config/base_setup/post_zsh
