#!/usr/bin/zsh

# Installing chezmoi to push local changes
echo Installing chezmoi
sh -c "$(curl -fsLS get.chezmoi.io)"
    
# Add entry to .zshrc to load config
echo '' >> ~/.zshrc
echo '# Include zsh configuration' >> ~/.zshrc
echo 'for file in ~/.config/zsh/*; do source "$file"; done' >> ~/.zshrc

echo 'Select the default editor to use in this machine:'
echo '1: nvim'
echo '2: emacs (standalone)'
echo '3: emacsclient (requires "emacs.service" user service running)'

echo "export EDITOR='nvim'" >> ~/.config/zsh/sh_variables

# install needed packages
sudo $PKG $INSTALL_CMD \
    sway \
    nvim \
    foot \
    bemenu \
    swaylock \
    swayidle \
    swaybg \
    tmux \
    brightnessctl \
    zsh-autosuggestions \
    zsh-syntax-highlighting \

# So nvim doesn't fart
touch .config/nvim/lua/snippets.lua

# Find another way to install fonts
# ttf-nerd-fonts-symbols

# Setting up catppuccin theme 
~/.config/base_setup/catppuccin_setup
