#!/usr/bin/zsh

set -e

# Installing chezmoi to push local changes
if [[ ! $(chezmoi --version) ]]; then
    echo Installing chezmoi
    sh -c "$(curl -fsLS get.chezmoi.io)"
fi

if [[ ! $(grep '#load_dot_conf_zsh' ~/.zshrc) ]]; then
    # Add entry to .zshrc to load config
    echo 'Include ~/.config/zsh/* in .zshrc' 
    echo '' >> ~/.zshrc
    echo '# Include zsh configuration: #load_dot_conf_zsh' >> ~/.zshrc
    echo 'for file in ~/.config/zsh/*; do source "$file"; done' >> ~/.zshrc
fi

grep -e '^export EDITOR=' ~/.config/zsh/sh_variables > /dev/null ||\
    echo 'export EDITOR=nvim' >> ~/.config/zsh/sh_variables

if [[ (-z $PKG) || (-z $INSTALL_CMD) ]] exit 1

echo 'Using sudo to install packages'

echo 'Installing sway and related'
# install needed packages
sudo $PKG $INSTALL_CMD \
    sway \
    swaylock \
    swayidle \
    swaybg \
    i3status \
    bemenu

echo 'Installing tool for screenshot scripting'
sudo $PKG $INSTALL_CMD \
    grim \
    slurp \
    wl-clipboard \

echo 'Installing additional programs'
sudo $PKG $INSTALL_CMD \
    nvim \
    foot \
    tmux \
    pamixer \
    brightnessctl \
    zsh-autosuggestions \
    zsh-syntax-highlighting \

# So nvim doesn't fart
touch .config/nvim/lua/snippets.lua

# Find another way to install fonts
# ttf-nerd-fonts-symbols

# Setting up catppuccin theme 
~/.config/base_setup/catppuccin_setup
